// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/16/2024, 11:45:58 PM
const configMerger = require("D:/Coding/real-estate/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":["presets/**/*.{js,vue,ts}"],"theme":{"extend":{"colors":{"primary-50":"rgb(var(--primary-50))","primary-100":"rgb(var(--primary-100))","primary-200":"rgb(var(--primary-200))","primary-300":"rgb(var(--primary-300))","primary-400":"rgb(var(--primary-400))","primary-500":"rgb(var(--primary-500))","primary-600":"rgb(var(--primary-600))","primary-700":"rgb(var(--primary-700))","primary-800":"rgb(var(--primary-800))","primary-900":"rgb(var(--primary-900))","primary-950":"rgb(var(--primary-950))","surface-0":"rgb(var(--surface-0))","surface-50":"rgb(var(--surface-50))","surface-100":"rgb(var(--surface-100))","surface-200":"rgb(var(--surface-200))","surface-300":"rgb(var(--surface-300))","surface-400":"rgb(var(--surface-400))","surface-500":"rgb(var(--surface-500))","surface-600":"rgb(var(--surface-600))","surface-700":"rgb(var(--surface-700))","surface-800":"rgb(var(--surface-800))","surface-900":"rgb(var(--surface-900))","surface-950":"rgb(var(--surface-950))"}}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Coding/real-estate/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding/real-estate/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding/real-estate/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding/real-estate/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Coding/real-estate/plugins/**/*.{js,ts,mjs}","D:/Coding/real-estate/composables/**/*.{js,ts,mjs}","D:/Coding/real-estate/utils/**/*.{js,ts,mjs}","D:/Coding/real-estate/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Coding/real-estate/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Coding/real-estate/app.config.{js,ts,mjs}"] }));

module.exports = config
